version: '3.4'

services:
  subscriptionapi:
    image: ${DOCKER_REGISTRY-}subscriptionapi
    build:
      context: .
      dockerfile: Subscriptionapi/Dockerfile
    ports:
      - "80:80" # Map port 80 on the host to port 80 on the container
    depends_on:
      - postgres # Ensure the PostgreSQL service starts first
    environment:
      - ConnectionStrings:Host=127.0.0.1;Port=5432;Database=subscriptionmanagment;Username=postgres;Password=123

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 on the container
    environment:
      POSTGRES_DB: subscriptionmanagment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
